# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Launchpad < Formula
  desc "Launchpad CLI — deploy apps to the PaaS platform"
  homepage "https://github.com/DND-IT/launchpad"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.2/launchpad_0.4.2_darwin_amd64.tar.gz"
      sha256 "995062e8a5964fbb03b4331b5ff50429eeffc6c4daa2218eae6318e52151bc5b"

      define_method(:install) do
        bin.install "launchpad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.2/launchpad_0.4.2_darwin_arm64.tar.gz"
      sha256 "742c155e1bdee58a1c029d56b1242a6dbb39d9ec15bac75c3ae963e739916eff"

      define_method(:install) do
        bin.install "launchpad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.2/launchpad_0.4.2_linux_amd64.tar.gz"
      sha256 "9a7cc7fb467c3f3e874ae85280fa968c991b674c2e12391906189c60a819ced5"
      define_method(:install) do
        bin.install "launchpad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.2/launchpad_0.4.2_linux_arm64.tar.gz"
      sha256 "210249374df560ef42a7d4df62aef584903a56d2dcd5d4de2c8402c9dcbcfcf4"
      define_method(:install) do
        bin.install "launchpad"
      end
    end
  end

  test do
    system "#{bin}/launchpad", "--version"
  end
end
