# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Launchpad < Formula
  desc "Launchpad CLI — deploy apps to the PaaS platform"
  homepage "https://github.com/DND-IT/launchpad"
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.3/launchpad_0.4.3_darwin_amd64.tar.gz"
      sha256 "b90777b92af247133babecb3374d2a661ffcc2aa39e5d4a58b3d3d79564bf710"

      define_method(:install) do
        bin.install "launchpad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.3/launchpad_0.4.3_darwin_arm64.tar.gz"
      sha256 "47a80da3ddd4e1f54d72e3c0dd96dfee42e267cc71d1a4ae4420bc58943531c0"

      define_method(:install) do
        bin.install "launchpad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.3/launchpad_0.4.3_linux_amd64.tar.gz"
      sha256 "8a5efd2ea2366cde9ae5928533b6c3f2469b89588549e5ffcf41cc7b31f5b657"
      define_method(:install) do
        bin.install "launchpad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DND-IT/launchpad/releases/download/0.4.3/launchpad_0.4.3_linux_arm64.tar.gz"
      sha256 "c261bdee7e31c36b6d046232eb5f30bbebb33f86336cba80849b6e2ba4370c63"
      define_method(:install) do
        bin.install "launchpad"
      end
    end
  end

  test do
    system "#{bin}/launchpad", "--version"
  end
end
